// Mocks generated by Mockito 5.4.6 from annotations
// in my_madamis_app/test/features/group_search/presentation/viewmodels/group_search_viewmodel_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:my_madamis_app/features/friends/domain/repositories/friends_repository.dart'
    as _i5;
import 'package:my_madamis_app/features/group_search/domain/entities/group_search_result.dart'
    as _i4;
import 'package:my_madamis_app/features/group_search/domain/repositories/group_search_repository.dart'
    as _i2;
import 'package:my_madamis_app/models/ModelProvider.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [GroupSearchRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockGroupSearchRepository extends _i1.Mock
    implements _i2.GroupSearchRepository {
  MockGroupSearchRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.GroupSearchResult>> findGroupScenarios(
          List<String>? friendIds) =>
      (super.noSuchMethod(
        Invocation.method(
          #findGroupScenarios,
          [friendIds],
        ),
        returnValue: _i3.Future<List<_i4.GroupSearchResult>>.value(
            <_i4.GroupSearchResult>[]),
      ) as _i3.Future<List<_i4.GroupSearchResult>>);
}

/// A class which mocks [FriendsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockFriendsRepository extends _i1.Mock implements _i5.FriendsRepository {
  MockFriendsRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i6.User>> searchUsers(String? query) => (super.noSuchMethod(
        Invocation.method(
          #searchUsers,
          [query],
        ),
        returnValue: _i3.Future<List<_i6.User>>.value(<_i6.User>[]),
      ) as _i3.Future<List<_i6.User>>);

  @override
  _i3.Future<void> followUser(String? followedUserId) => (super.noSuchMethod(
        Invocation.method(
          #followUser,
          [followedUserId],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> unfollowUser(String? followedUserId) => (super.noSuchMethod(
        Invocation.method(
          #unfollowUser,
          [followedUserId],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<List<_i6.User>> fetchFollowingUsers() => (super.noSuchMethod(
        Invocation.method(
          #fetchFollowingUsers,
          [],
        ),
        returnValue: _i3.Future<List<_i6.User>>.value(<_i6.User>[]),
      ) as _i3.Future<List<_i6.User>>);

  @override
  _i3.Future<int> getFollowingCount() => (super.noSuchMethod(
        Invocation.method(
          #getFollowingCount,
          [],
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);
}
