// Mocks generated by Mockito 5.4.6 from annotations
// in my_madamis_app/test/features/scenario_logbook/domain/usecases/get_scenarios_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:flutter/material.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:my_madamis_app/features/scenario_logbook/domain/entities/scenario.dart'
    as _i4;
import 'package:my_madamis_app/features/scenario_logbook/domain/entities/user_scenario.dart'
    as _i6;
import 'package:my_madamis_app/features/scenario_logbook/domain/repositories/scenario_repository.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [ScenarioRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockScenarioRepository extends _i1.Mock
    implements _i2.ScenarioRepository {
  MockScenarioRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.Scenario>> fetchScenarios({
    required int? page,
    int? limit = 50,
    String? searchTerm,
    _i5.RangeValues? playerCountRange,
    _i4.GmRequirement? gmRequirement,
    String? authorName,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchScenarios,
          [],
          {
            #page: page,
            #limit: limit,
            #searchTerm: searchTerm,
            #playerCountRange: playerCountRange,
            #gmRequirement: gmRequirement,
            #authorName: authorName,
          },
        ),
        returnValue: _i3.Future<List<_i4.Scenario>>.value(<_i4.Scenario>[]),
      ) as _i3.Future<List<_i4.Scenario>>);

  @override
  _i3.Future<List<String>> fetchAllAuthorNames() => (super.noSuchMethod(
        Invocation.method(
          #fetchAllAuthorNames,
          [],
        ),
        returnValue: _i3.Future<List<String>>.value(<String>[]),
      ) as _i3.Future<List<String>>);

  @override
  _i3.Future<List<_i6.UserScenario>> fetchMyList() => (super.noSuchMethod(
        Invocation.method(
          #fetchMyList,
          [],
        ),
        returnValue:
            _i3.Future<List<_i6.UserScenario>>.value(<_i6.UserScenario>[]),
      ) as _i3.Future<List<_i6.UserScenario>>);

  @override
  _i3.Future<List<_i6.UserScenario>> fetchUserScenarios(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchUserScenarios,
          [userId],
        ),
        returnValue:
            _i3.Future<List<_i6.UserScenario>>.value(<_i6.UserScenario>[]),
      ) as _i3.Future<List<_i6.UserScenario>>);

  @override
  _i3.Future<void> updateUserScenarioStatus(
    String? scenarioId,
    _i6.UserScenarioStatus? status,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateUserScenarioStatus,
          [
            scenarioId,
            status,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> removeUserScenarioStatus(String? scenarioId) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeUserScenarioStatus,
          [scenarioId],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}
