// Mocks generated by Mockito 5.4.6 from annotations
// in my_madamis_app/test/mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:amplify_flutter/amplify_flutter.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:my_madamis_app/features/auth/domain/repositories/auth_repository.dart'
    as _i4;
import 'package:my_madamis_app/features/profile/domain/entities/user_profile.dart'
    as _i3;
import 'package:my_madamis_app/features/profile/domain/repositories/profile_repository.dart'
    as _i6;
import 'package:my_madamis_app/features/settings/domain/repositories/settings_repository.dart'
    as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeSignUpResult_0 extends _i1.SmartFake implements _i2.SignUpResult {
  _FakeSignUpResult_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSignInResult_1 extends _i1.SmartFake implements _i2.SignInResult {
  _FakeSignInResult_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUserProfile_2 extends _i1.SmartFake implements _i3.UserProfile {
  _FakeUserProfile_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i4.AuthRepository {
  MockAuthRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.SignUpResult> signUp({
    required String? email,
    required String? password,
    required String? username,
    String? bio,
    String? twitterId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #signUp,
          [],
          {
            #email: email,
            #password: password,
            #username: username,
            #bio: bio,
            #twitterId: twitterId,
          },
        ),
        returnValue: _i5.Future<_i2.SignUpResult>.value(_FakeSignUpResult_0(
          this,
          Invocation.method(
            #signUp,
            [],
            {
              #email: email,
              #password: password,
              #username: username,
              #bio: bio,
              #twitterId: twitterId,
            },
          ),
        )),
      ) as _i5.Future<_i2.SignUpResult>);

  @override
  _i5.Future<_i2.SignUpResult> confirmSignUp({
    required String? username,
    required String? confirmationCode,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #confirmSignUp,
          [],
          {
            #username: username,
            #confirmationCode: confirmationCode,
          },
        ),
        returnValue: _i5.Future<_i2.SignUpResult>.value(_FakeSignUpResult_0(
          this,
          Invocation.method(
            #confirmSignUp,
            [],
            {
              #username: username,
              #confirmationCode: confirmationCode,
            },
          ),
        )),
      ) as _i5.Future<_i2.SignUpResult>);

  @override
  _i5.Future<void> resendSignUpCode({required String? username}) =>
      (super.noSuchMethod(
        Invocation.method(
          #resendSignUpCode,
          [],
          {#username: username},
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<_i2.SignInResult> signIn({
    required String? username,
    required String? password,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #signIn,
          [],
          {
            #username: username,
            #password: password,
          },
        ),
        returnValue: _i5.Future<_i2.SignInResult>.value(_FakeSignInResult_1(
          this,
          Invocation.method(
            #signIn,
            [],
            {
              #username: username,
              #password: password,
            },
          ),
        )),
      ) as _i5.Future<_i2.SignInResult>);

  @override
  _i5.Future<void> signOut() => (super.noSuchMethod(
        Invocation.method(
          #signOut,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<List<_i2.AuthUserAttribute>> getCurrentUserAttributes() =>
      (super.noSuchMethod(
        Invocation.method(
          #getCurrentUserAttributes,
          [],
        ),
        returnValue: _i5.Future<List<_i2.AuthUserAttribute>>.value(
            <_i2.AuthUserAttribute>[]),
      ) as _i5.Future<List<_i2.AuthUserAttribute>>);
}

/// A class which mocks [ProfileRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockProfileRepository extends _i1.Mock implements _i6.ProfileRepository {
  MockProfileRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i3.UserProfile> fetchUserProfile() => (super.noSuchMethod(
        Invocation.method(
          #fetchUserProfile,
          [],
        ),
        returnValue: _i5.Future<_i3.UserProfile>.value(_FakeUserProfile_2(
          this,
          Invocation.method(
            #fetchUserProfile,
            [],
          ),
        )),
      ) as _i5.Future<_i3.UserProfile>);

  @override
  _i5.Future<void> updateUserProfile(_i3.UserProfile? profile) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateUserProfile,
          [profile],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}

/// A class which mocks [SettingsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockSettingsRepository extends _i1.Mock
    implements _i7.SettingsRepository {
  MockSettingsRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<void> updateEmail(String? newEmail) => (super.noSuchMethod(
        Invocation.method(
          #updateEmail,
          [newEmail],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> confirmUpdateEmail(String? confirmationCode) =>
      (super.noSuchMethod(
        Invocation.method(
          #confirmUpdateEmail,
          [confirmationCode],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> updatePassword({
    required String? oldPassword,
    required String? newPassword,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updatePassword,
          [],
          {
            #oldPassword: oldPassword,
            #newPassword: newPassword,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}
