// Mocks generated by Mockito 5.4.6 from annotations
// in my_madamis_app/test/features/scenario_logbook/presentation/notifiers/user_scenario_status_notifier_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:my_madamis_app/features/scenario_logbook/domain/entities/user_scenario.dart'
    as _i4;
import 'package:my_madamis_app/features/scenario_logbook/domain/usecases/get_my_list_usecase.dart'
    as _i2;
import 'package:my_madamis_app/features/scenario_logbook/domain/usecases/update_user_scenario_status_usecase.dart'
    as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [GetMyListUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetMyListUseCase extends _i1.Mock implements _i2.GetMyListUseCase {
  MockGetMyListUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.UserScenario>> call() => (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
        ),
        returnValue:
            _i3.Future<List<_i4.UserScenario>>.value(<_i4.UserScenario>[]),
      ) as _i3.Future<List<_i4.UserScenario>>);
}

/// A class which mocks [UpdateUserScenarioStatusUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockUpdateUserScenarioStatusUseCase extends _i1.Mock
    implements _i5.UpdateUserScenarioStatusUseCase {
  MockUpdateUserScenarioStatusUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> call(
    String? scenarioId,
    _i4.UserScenarioStatus? newStatus,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [
            scenarioId,
            newStatus,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}
