// Mocks generated by Mockito 5.4.6 from annotations
// in my_madamis_app/test/features/player_finder/presentation/viewmodels/player_finder_viewmodel_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:my_madamis_app/features/player_finder/data/repositories/player_finder_repository.dart'
    as _i2;
import 'package:my_madamis_app/features/player_finder/domain/entities/searched_user.dart'
    as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [PlayerFinderRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockPlayerFinderRepository extends _i1.Mock
    implements _i2.PlayerFinderRepository {
  MockPlayerFinderRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.SearchedUser>> findUnplayedFriends(
    String? scenarioId, {
    String? mode,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #findUnplayedFriends,
          [scenarioId],
          {#mode: mode},
        ),
        returnValue:
            _i3.Future<List<_i4.SearchedUser>>.value(<_i4.SearchedUser>[]),
      ) as _i3.Future<List<_i4.SearchedUser>>);
}
